[build]
publish = "public"
command = "hugo mod get -u && hugo --baseURL $URL --gc"

[context.production.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
GO_VERSION = "1.14"


[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "data"

    # All the feeds we wish to gather for use in the build

    [[plugins.inputs.feeds]]
      name = "perr-analytics"
      url = "https://perr-analytics.netlify.app/.netlify/functions/fetch"
      ttl = 3600
