[build]
publish = "public"

[context.production.environment]
command = "hugo mod get -u && hugo --baseURL $URL --gc"
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
GO_VERSION = "1.15"
NODE_VERSION = "12.20.0"


[context.branch-deploy]
command = "hugo mod get -u && hugo --baseURL $DEPLOY_PRIME_URL"
HUGO_VERSION = "0.80.0"
GO_VERSION = "1.15"
NODE_VERSION = "12.20.0"


[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "data"

    # All the feeds we wish to gather for use in the build

    [[plugins.inputs.feeds]]
     name = "analytics"
     url = "https://perr-analytics.netlify.app/.netlify/functions/fetch"
     ttl = 3600
