[build]
publish = "public"
command = "hugo mod get -u && hugo --baseURL $URL --gc"

[build.environment]
NODE_VERSION = "12.20.0"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
GO_VERSION = "1.15"

[context.branch-deploy]
  command = "hugo mod get -u && hugo --gc"
  HUGO_VERSION = "0.80.0"
  GO_VERSION = "1.15"

[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Where should data files reside
    dataDir = "data"

    # All the feeds we wish to gather for use in the build

    [[plugins.inputs.feeds]]
     name = "analytics"
     url = "https://perr-analytics.netlify.app/.netlify/functions/fetch"
     ttl = 3600
