backend:
  name: git-gateway
media_folder: static/img
public_folder: /img
media_library:
  name: cloudinary
  output_filename_only: true
  config:
      cloud_name: portuguese-economic-journal
      api_key: 197739781531424

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/posts'
    create: true
    slug: '{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'date', format: 'YYYY-MM-DD' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'curators'
    label: 'Curators'
    folder: 'data/curators'
    create: true
    preview: false
    extension: 'yaml'
    format: 'yaml'
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Bio', name: 'bio', widget: 'text' }
      - { label: 'Picture', name: 'picture', widget: 'image' }
      - { label: 'Links', name: 'links', widget: 'list', summary: '{{fields.title}}',
          fields:
        [
          {label: 'Link', name: 'link', widget: 'string'},
          {label: 'Title', name: 'title', widget: 'string'}
        ]}

